services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bhoo
      - MONGO_INITDB_ROOT_PASSWORD=bhoo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bhoo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bhoo
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://bhoo:bhoo@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongodb

volumes:
  mongo: {}
